# syntax=docker/dockerfile:1
#
# The instrument store image.
#
# Separate from Dockerfile.rust, which is the gate runner. This one produces the
# thing that runs; that one produces answers about it.

ARG RUST_VERSION=1.90
ARG NODE_VERSION=22.23.3
# The plugin UI kit, meridian-ui, at a pinned commit of its public repository.
# Moving the kit is moving this.
ARG MERIDIAN_UI_REV=c51f6318ebb8a2ff2049a31a394930109046df9d

# The kit the dashboard serves at /.meridian/ui/<version>/ on every plugin host
# and its own (spec/plugin-pages-share-one-kit.md, Q2), built from its source
# as meridian-ui's own build does, never vendored here. Its build reads the
# brand's tokens from the generated/ it commits, and needs nothing installed.
FROM node:${NODE_VERSION}-alpine AS ui
ARG MERIDIAN_UI_REV
ADD https://github.com/open-meridian/meridian-ui.git#${MERIDIAN_UI_REV} /ui
WORKDIR /ui
RUN node tools/build.mjs

FROM rust:${RUST_VERSION}-slim-bookworm AS build
RUN apt-get update \
 && apt-get install -y --no-install-recommends git ca-certificates \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /w
COPY Cargo.toml Cargo.lock ./
COPY crates/ crates/
# The contract the sidecar and the broker grant from, compiled in
# (decisions/020): who publishes and subscribes to what, and which names are
# roles. Generated by meridian-design; the only part of deploy/ the binaries
# read.
COPY deploy/topics.tsv deploy/roles.tsv deploy/
# The release every binary reports, compiled in (meridian_runtime::VERSION):
# the publish workflow's chart version and commit. Empty, as any other build
# leaves it, a binary says its crate version marked `-dev`. Declared here, by
# the step that reads it, so a new version rebuilds nothing before it.
ARG MERIDIAN_VERSION=
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/w/target \
    cargo build --release --locked -p meridian-runtime \
 && cp target/release/meridian-street target/release/meridian-bor target/release/meridian-instrument \
       target/release/meridian-conductor target/release/meridian-sidecar \
       target/release/meridian-dashboard \
       target/release/meridian-first-run target/release/meridian-broker-config \
       target/release/meridian-launcher \
       /usr/local/bin/
# Asked of each binary rather than trusted to the compiler: the target
# directory is a cache that outlives a build, and a binary it kept from the
# last one would report that one's version. An image that would say a release
# it is not is never made.
RUN set -eu; for bin in /usr/local/bin/meridian-*; do \
      said="$("$bin" --version)"; \
      case "${MERIDIAN_VERSION}" in \
        "") case "$said" in *-dev) ;; *) echo "$bin says $said; built with no version" >&2; exit 1 ;; esac ;; \
        *) [ "$said" = "$MERIDIAN_VERSION" ] || { echo "$bin says $said; built as $MERIDIAN_VERSION" >&2; exit 1; } ;; \
      esac; \
    done

# The plugin harness (deploy/harness/README.md), its own image and files only:
# the compose file, runner and SQL a plugin's own end-to-end check copies out
# and runs against the runtime image of the same commit, which publish tags
# both with. Nothing here runs, so it holds no shell and no binary, and the
# runtime image below carries none of it: a deployment's pods never hold a
# test deployment (kernel/the-plugin-harness-is-its-own-image).
#
# Before `runtime`, which stays the last stage, so a build naming no target
# still makes the runtime image.
FROM scratch AS harness
LABEL org.opencontainers.image.source=https://github.com/open-meridian/meridian-core \
      org.opencontainers.image.description="The plugin harness: files to copy out, never to run"
COPY deploy/harness/compose.yaml deploy/harness/harness.py deploy/harness/street.sql \
     deploy/harness/book.sql deploy/harness/tickets.sql deploy/harness/README.md /harness/

FROM debian:bookworm-slim AS runtime
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# The private key lives here, on a volume, and never leaves the container.
RUN mkdir -p /var/lib/meridian
VOLUME /var/lib/meridian

# Where plugins dial.

# One image, three components. They share a build and a base, and differ in
# which one an orchestrator starts: a deployment upgrades them on their own
# schedules by moving one Deployment's tag, not by pulling three images that
# were built from different commits.
COPY --from=build /usr/local/bin/meridian-street /usr/local/bin/meridian-street
COPY --from=build /usr/local/bin/meridian-bor /usr/local/bin/meridian-bor
COPY --from=build /usr/local/bin/meridian-instrument /usr/local/bin/meridian-instrument
COPY --from=build /usr/local/bin/meridian-conductor /usr/local/bin/meridian-conductor
COPY --from=build /usr/local/bin/meridian-sidecar /usr/local/bin/meridian-sidecar
COPY --from=build /usr/local/bin/meridian-dashboard /usr/local/bin/meridian-dashboard
COPY --from=build /usr/local/bin/meridian-first-run /usr/local/bin/meridian-first-run
COPY --from=build /usr/local/bin/meridian-broker-config /usr/local/bin/meridian-broker-config
COPY --from=build /usr/local/bin/meridian-launcher /usr/local/bin/meridian-launcher
# One directory per version, where the dashboard looks (MERIDIAN_UI_DIR).
COPY --from=ui /ui/dist/ /usr/share/meridian/ui/

# No default: a component is chosen, never inherited. An image that starts
# something when nobody said which is an image that starts the wrong thing.
ENTRYPOINT []
