//! Generated by meridian-design's tools/generate_typed_operations.py from the matrix and
//! the domain protos (spec/typed-sidecar-operations). Do not edit.
//!
//! One method per operation: the plugin's params read as the domain
//! message, which they are on the wire, the stamped fields set, and the
//! message sent through the sidecar's one path onto the bus.

use meridian_domain::v1 as domain;
use meridian_pb::plugin::v1 as plugin;
use tonic::{Request, Response, Status};

use crate::service::Sidecar;

#[tonic::async_trait]
impl plugin::plugin_operations_server::PluginOperations for Sidecar {
    /// W2.1: `platform.custody.{instance}.event.sync-status`.
    async fn report_sync_status(
        &self,
        request: Request<plugin::ReportSyncStatusParams>,
    ) -> Result<Response<plugin::Published>, Status> {
        let mut message: domain::SyncStatusEvent = self.as_domain(request.into_inner())?;
        message.account_id = self.linked_account(&message.external_account_id).await?;
        self.publish_typed("platform.custody.{instance}.event.sync-status", "meridian.v1.SyncStatusEvent", message).await
    }

    /// W2.2: `platform.street.command.record-statement`.
    async fn record_holdings_statement(
        &self,
        request: Request<plugin::RecordHoldingsStatementParams>,
    ) -> Result<Response<plugin::RecordHoldingsStatementResult>, Status> {
        let mut params = request.into_inner();
        let acting_for = params.acting_for.take();
        let message: domain::RecordHoldingsStatementRequest = self.as_domain(params)?;
        let account = None;
        self.command_typed("platform.street.command.record-statement", "meridian.v1.RecordHoldingsStatementRequest", message, account, acting_for).await
    }

    /// W2.3: `platform.street.command.record-holding`.
    async fn record_holding(
        &self,
        request: Request<plugin::RecordHoldingParams>,
    ) -> Result<Response<plugin::RecordHoldingResult>, Status> {
        let mut params = request.into_inner();
        let acting_for = params.acting_for.take();
        let mut message: domain::RecordHoldingRequest = self.as_domain(params)?;
        message.account_id = self.linked_account(&message.external_account_id).await?;
        let account = Some(message.account_id.clone());
        self.command_typed("platform.street.command.record-holding", "meridian.v1.RecordHoldingRequest", message, account, acting_for).await
    }

    /// W3.1: `platform.reference.query.resolve-identifier`.
    async fn resolve_identifier(
        &self,
        request: Request<plugin::ResolveIdentifierParams>,
    ) -> Result<Response<plugin::ResolveIdentifierResult>, Status> {
        let message: domain::ResolveIdentifierRequest = self.as_domain(request.into_inner())?;
        self.call_typed("platform.reference.query.resolve-identifier", "meridian.v1.ResolveIdentifierRequest", message).await
    }

    /// W3.2: `platform.reference.event.instrument-missing`.
    async fn report_missing_instrument(
        &self,
        request: Request<plugin::ReportMissingInstrumentParams>,
    ) -> Result<Response<plugin::Published>, Status> {
        let mut message: domain::MissingInstrumentDetectedEvent = self.as_domain(request.into_inner())?;
        message.publisher_instance_id = self.instance_id().to_string();
        self.publish_typed("platform.reference.event.instrument-missing", "meridian.v1.MissingInstrumentDetectedEvent", message).await
    }
}
