//! The typed operations' hand-written half (spec/typed-sidecar-operations).
//!
//! `operations.rs` is generated by meridian-design, one method per operation,
//! and each calls into this: read the plugin's params as the domain message,
//! stamp what only the sidecar knows, check the grant, send. This is the part
//! that does not vary by operation, which is why it is written once and the
//! part that does is generated.
//!
//! The deployment's configuration is the exception to a plugin acting as
//! itself: a command or query in the `config` domain -- linking an external
//! account, reading the deployment's accounts to link it to (W6.4) -- is
//! admitted only acting for an admin of the plugin, in a session opened by
//! Manage (the claims' level `admin`), a link only for an external account the
//! plugin itself reported (W2.8), and one naming a new account only for a
//! deployment admin. **Two named exceptions** (contract v13; W4.9's notes,
//! W4.12): filing a ticket and reading what the plugin filed are admitted
//! acting for a person at any level, and never as the plugin itself
//! ([`FOR_A_PERSON_AT_ANY_LEVEL`], the one place they are named).
//!
//! **A session's level decides what is sent for the person** (W4.9, W6.9).
//! Under `write` (Open), a command on an account in the write set; under
//! `admin` (Manage), the accounts read and the link, and nothing else, since
//! `admin` reaches no account's data; under `read` (View), nothing. An
//! assertion naming no level holds nothing.
//!
//! **By the role holding the act** (contract v15, decisions/033): the plugin
//! names no role on what it sends; the sidecar asks which of the plugin's
//! roles hold the topic among their generated grants, and admits the command
//! for `write` -- or the `config` act for `admin` -- on one of those roles in
//! the claims' per-role entries, the account among that role's write
//! accounts. Refused otherwise, naming each role that grants it and what the
//! person holds on it ("RecordHoldingsStatement is custody's, and Ada holds
//! read on custody"). Claims with no per-role entry are read as the one
//! role's on a plugin holding one, and refused on a plugin holding several.
//! Each act admitted for a person is logged with its level and the roles it
//! was admitted under.
//!
//! **A read is within the plugin's read scope** (W4.4, W4.11). Every query is
//! stamped with the scope, marked as applying, so the store answers an empty
//! one with nothing; and one naming an account outside it -- the field
//! matrix/scoped.tsv names, which the generated operation hands here -- is
//! refused before it leaves.
//!
//! A refusal is the call's gRPC status, chosen by what the caller should do
//! about it: `permission_denied` for a topic none of the plugin's roles
//! grants, an account outside the read scope, or the deployment's
//! configuration without a deployment admin,
//! `invalid_argument` for a number the wire does not carry,
//! `failed_precondition` for an external account nobody has linked,
//! `unavailable` when nothing serves the topic, `deadline_exceeded` when it
//! did not answer in time, `aborted` when it answered with a refusal.
//!
//! Where one status covers refusals a plugin must tell apart, the refusal
//! carries a reason code beside it, from the typed-operations refusal
//! catalogue (spec/typed-sidecar-operations, section 7): a `Refusal`, encoded,
//! in the trailing metadata [`REFUSAL_METADATA`]. A plugin acts on the code;
//! the words are for a person reading a log, and may change.

use meridian_bus::{BusError, Stamp};
use meridian_domain::exact::Exact;
use meridian_domain::v1 as domain;
use meridian_domain::v1::{ExternalAccountsEvent, LinkExternalAccountRequest};
use meridian_pb::plugin::v1 as plugin;
use meridian_pb::v1::{AccessLevel, CallerAssertion, CallerClaims, Refusal, RefusalReason};
use prost::Message;
use tonic::metadata::{MetadataMap, MetadataValue};
use tonic::{Code, Response, Status};

use crate::service::Sidecar;

/// The deployment's configuration: what a plugin sends here it sends only for
/// an admin of the plugin (W6.4).
const CONFIGURATION: &str = "platform.config.";
const LINK_EXTERNAL_ACCOUNT: &str = "platform.config.command.link-external-account";
/// A plugin's ticket, filed with the dashboard (PluginFilesTicket, W4.12).
pub(crate) const FILE_TICKET: &str = "platform.config.command.file-ticket";
/// What became of the tickets a plugin filed (ReadFiledTickets, W4.12).
pub(crate) const FILED_TICKETS: &str = "platform.config.query.filed-tickets";
/// The `config` topics sent for a person at any level -- `read`, `write` or
/// `admin` -- rather than only for an admin of the plugin: the two named
/// exceptions of W4.9's notes (contract v13, ruled 2026-10-03). Every other
/// `config` command and query stays an admin's, and none is ever sent for
/// the plugin as itself.
pub(crate) const FOR_A_PERSON_AT_ANY_LEVEL: [&str; 2] = [FILE_TICKET, FILED_TICKETS];
/// Where a plugin says which external accounts its connection reaches (W2.8).
const EXTERNAL_ACCOUNTS: &str = "meridian.v1.ExternalAccountsEvent";

// The tonic surface already returns `Result<_, Status>` everywhere; boxing the
// error here alone would buy nothing.
#[allow(clippy::result_large_err)]
impl Sidecar {
    pub(crate) fn instance_id(&self) -> &str {
        &self.identity.instance_id
    }

    /// A plugin's params, read as the domain message they are on the wire.
    ///
    /// The params keep every field number of the domain message and drop only
    /// the stamped ones, so their encoding is the domain message's with those
    /// unset. Refused before registration, as every operation is.
    pub(crate) fn as_domain<P: Message, D: Message + Default>(
        &self,
        params: P,
    ) -> Result<D, Status> {
        self.admitted()?;
        D::decode(params.encode_to_vec().as_slice()).map_err(|failed| {
            Status::internal(format!(
                "the params did not read as the domain message: {failed}"
            ))
        })
    }

    /// A number the plugin sent, refused naming its field when it is outside
    /// what the wire carries: more than 18 decimal places, or 38 digits
    /// (decisions/023). The generated SDKs refuse these before sending; this
    /// is for a plugin that built its params by hand, and it runs before
    /// anything is stamped, so a malformed row never reaches the conductor or
    /// the street store. Nothing is rounded. An unset number is not checked
    /// here: whether one is required is the receiving component's to say.
    pub(crate) fn exact(
        &self,
        field: &str,
        value: Option<&meridian_pb::v1::Decimal>,
    ) -> Result<(), Status> {
        let Some(value) = value else {
            return Ok(());
        };
        Exact::from_wire(value).map(|_| ()).map_err(|out_of_range| {
            let refusal = format!("{field} {out_of_range}; it is refused rather than rounded");
            self.note_refusal(&refusal);
            Status::invalid_argument(refusal)
        })
    }

    /// An amount, whose number is checked as any other is, under the name of
    /// the field the plugin set.
    pub(crate) fn exact_money(
        &self,
        field: &str,
        value: Option<&domain::Money>,
    ) -> Result<(), Status> {
        self.exact(field, value.and_then(|money| money.amount.as_ref()))
    }

    /// An enum value the plugin sent, refused naming its field when the
    /// contract does not define it: proto3 carries any number, so an asset
    /// class of 99 would otherwise reach the bus as though it were one
    /// (sdk-contract/asset-class-is-an-enum). The generated SDKs refuse these
    /// before sending; this is for a plugin that built its params by hand.
    /// Zero, the unspecified value, is defined: whether one is required is
    /// the receiving component's to say.
    pub(crate) fn known(&self, field: &str, value: i32, defined: bool) -> Result<(), Status> {
        if defined {
            return Ok(());
        }
        let refusal = format!("{field} is {value}, which the contract does not define");
        self.note_refusal(&refusal);
        Err(Status::invalid_argument(refusal))
    }

    /// The topic this instance sends on: its own identifier where the row
    /// names `{instance}`, so a plugin can speak only as itself.
    fn own_topic(&self, topic: &str) -> String {
        topic.replace("{instance}", self.instance_id())
    }

    fn granted(&self, topic: &str) -> Result<(), Status> {
        let registration = self.admitted()?;
        if registration.grants.may_publish(topic) {
            return Ok(());
        }
        let held = if registration.roles.is_empty() {
            "no role".to_string()
        } else {
            registration.roles.join(", ")
        };
        let refusal = format!("no grant for {topic}: this plugin holds {held}");
        self.note_refusal(&refusal);
        Err(Status::permission_denied(refusal))
    }

    /// An event: checked, published, and its identifier handed back.
    pub(crate) async fn publish_typed<D: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
    ) -> Result<Response<plugin::Published>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let message = self.kept_at_the_edge(payload_type, message)?;
        let payload = message.encode_to_vec();
        let message_id = self
            .bus
            .publish(&topic, payload_type, payload.clone(), None, None)
            .map_err(refused)?;
        if payload_type == EXTERNAL_ACCOUNTS {
            self.keep_reported(&payload);
        }
        Ok(Response::new(plugin::Published { message_id }))
    }

    /// The external accounts the plugin just said it reaches, the whole list,
    /// in place of the last: the ones a link may name (W2.8, W6.4).
    fn keep_reported(&self, payload: &[u8]) {
        if let Ok(event) = ExternalAccountsEvent::decode(payload) {
            *self.reported.lock().expect("reported lock poisoned") = event
                .accounts
                .into_iter()
                .map(|account| account.external_account_id)
                .collect();
        }
    }

    /// A query: checked, asked, and the domain reply handed back as its
    /// plugin-facing mirror, which it is on the wire. One of the deployment's
    /// configuration is asked only for a deployment admin, who is stamped on
    /// it (W6.4); any other carries no person (decisions/014). Every one
    /// carries the plugin's read scope, marked as applying, and one naming
    /// `account` outside it is refused here, first (W4.4, W4.11); `account`
    /// is `None` for a query matrix/scoped.tsv declares unscoped, and empty
    /// for one naming none, which the store answers for the whole scope.
    pub(crate) async fn call_typed<D: Message, R: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
        account: Option<String>,
        acting_for: Option<CallerAssertion>,
    ) -> Result<Response<R>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let (subject, delegation, client) = if topic.starts_with(CONFIGURATION) {
            let (claims, roles) =
                self.vouched_for_configuration(&topic, payload_type, acting_for.as_ref(), self.clock.now_ns())?;
            tracing::info!(
                instance = self.instance_id(),
                topic,
                by = claims.subject,
                at_level = level_named(claims.level),
                roles = roles.join(","),
                "read for a person"
            );
            (claims.subject, claims.delegation_id, claims.client_name)
        } else {
            (String::new(), String::new(), String::new())
        };
        let scope = self
            .configuration(self.clock.now_ns())
            .await?
            .read_account_ids;
        if let Some(account) = account.filter(|account| !account.is_empty()) {
            if !scope.contains(&account) {
                let refusal = format!("{account} is not in this plugin's read scope");
                self.note_refusal(&refusal);
                return Err(Status::permission_denied(refusal));
            }
        }
        let stamp = Stamp {
            acting_for_subject: subject,
            acting_through_delegation: delegation,
            acting_through_client: client,
            account_scope: Some(scope),
        };
        let (_, payload) = self
            .bus
            .call_stamped(
                &topic,
                payload_type,
                message.encode_to_vec(),
                None,
                None,
                &stamp,
            )
            .await
            .map_err(refused)?;
        mirrored(payload)
    }

    /// A command: checked against the grant, against the plugin's write scope
    /// for the account it names, and -- when it is sent for a person (W4.9) --
    /// against what the dashboard vouched that person may write; then asked,
    /// with the person stamped on the envelope. One to the deployment's
    /// configuration is checked instead against the person being a deployment
    /// admin, and a link against what the plugin reported (W6.4).
    pub(crate) async fn command_typed<D: Message + Default, R: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
        account: Option<String>,
        acting_for: Option<CallerAssertion>,
    ) -> Result<Response<R>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let message = self.kept_at_the_edge(payload_type, message)?;
        self.statement_stands(payload_type, &message.encode_to_vec())?;
        // A command naming no account names none: a statement from a plugin
        // built before v7 is admitted with no account (crate::older).
        let account = account.filter(|account| !account.is_empty());
        let now = self.clock.now_ns();
        if topic.starts_with(CONFIGURATION) {
            // An admin's act on the deployment's configuration, not a write
            // to an account: a link names an account nothing may write through
            // this plugin yet, since the link is what grants it (W4.11).
            let (claims, roles) =
                self.vouched_for_configuration(&topic, payload_type, acting_for.as_ref(), now)?;
            if topic == LINK_EXTERNAL_ACCOUNT {
                self.reported_by_this_plugin(&message.encode_to_vec(), now)
                    .await?;
                self.names_a_new_account_only_for_a_deployment_admin(
                    &message.encode_to_vec(),
                    &claims,
                )?;
            }
            tracing::info!(
                instance = self.instance_id(),
                topic,
                by = claims.subject,
                at_level = level_named(claims.level),
                roles = roles.join(","),
                "sent for a person"
            );
            return self.ask_for(&topic, payload_type, message, &claims).await;
        }
        if let Some(account) = &account {
            let configuration = self.configuration(now).await?;
            if !configuration.write_account_ids.contains(account) {
                let refusal = format!(
                    "account {account} is outside this plugin's write scope: nobody may write \
                     it through this plugin"
                );
                self.note_refusal(&refusal);
                return Err(Status::permission_denied(refusal));
            }
        }
        let claims = match acting_for {
            None => CallerClaims::default(),
            Some(assertion) => {
                let (claims, roles) = self.vouched_writer(
                    &topic,
                    payload_type,
                    &assertion,
                    account.as_deref(),
                    now,
                )?;
                tracing::info!(
                    instance = self.instance_id(),
                    topic,
                    by = claims.subject,
                    at_level = "write",
                    roles = roles.join(","),
                    "sent for a person"
                );
                claims
            }
        };
        self.ask_for(&topic, payload_type, message, &claims).await
    }

    /// Asked, with the person stamped on the envelope -- and the delegation
    /// they acted through, when the assertion named one (W4.9, contract v9),
    /// with its client's name beside it (contract v10) -- and the reply read
    /// as its plugin-facing mirror. Default claims are
    /// the plugin acting as itself: nobody stamped.
    async fn ask_for<D: Message, R: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
        claims: &CallerClaims,
    ) -> Result<Response<R>, Status> {
        let stamp = Stamp {
            acting_for_subject: claims.subject.clone(),
            acting_through_delegation: if claims.subject.is_empty() {
                String::new()
            } else {
                claims.delegation_id.clone()
            },
            acting_through_client: if claims.subject.is_empty() || claims.delegation_id.is_empty() {
                String::new()
            } else {
                claims.client_name.clone()
            },
            account_scope: None,
        };
        let (_, payload) = self
            .bus
            .call_stamped(
                topic,
                payload_type,
                message.encode_to_vec(),
                None,
                None,
                &stamp,
            )
            .await
            .map_err(refused)?;
        mirrored(payload)
    }

    /// The claims a `config` topic is sent for, or the refusal: a person at
    /// any level for the two named exceptions, an admin of this plugin in a
    /// session opened by Manage for every other, and never the plugin as
    /// itself (W4.9's notes, W4.12).
    /// With the roles it was admitted under, for the log: none for the two
    /// named exceptions, admitted at any level on any role.
    pub(crate) fn vouched_for_configuration(
        &self,
        topic: &str,
        payload_type: &str,
        acting_for: Option<&CallerAssertion>,
        now_ns: i64,
    ) -> Result<(CallerClaims, Vec<String>), Status> {
        if FOR_A_PERSON_AT_ANY_LEVEL.contains(&topic) {
            self.vouched_person(topic, acting_for, now_ns)
                .map(|claims| (claims, Vec::new()))
        } else {
            self.vouched_admin(topic, payload_type, acting_for, now_ns)
        }
    }

    /// Which of this plugin's roles hold `topic` among their generated
    /// grants (decisions/033, point 3): what a person's act is admitted by.
    fn roles_granting(&self, topic: &str) -> Vec<String> {
        self.contract
            .roles_granting(&self.identity.roles, topic)
    }

    /// Claims carrying no per-role entry -- from a dashboard older than this
    /// sidecar, during an upgrade's roll -- are read as the one role's on a
    /// plugin holding one, exactly the check before v15; on a plugin holding
    /// several, nothing is sent for the person until they carry roles. Fail
    /// closed (W4.9).
    fn without_roles(&self, claims: &CallerClaims) -> Result<(), Status> {
        if !claims.roles.is_empty() || self.identity.roles.len() <= 1 {
            return Ok(());
        }
        let refusal = format!(
            "{}'s claims carry no level per role, and {} holds {}: nothing is sent for a person \
             on a plugin holding several roles until the claims say their level on each",
            who(claims),
            self.instance_id(),
            self.identity.roles.join(" and ")
        );
        self.note_refusal(&refusal);
        Err(Status::permission_denied(refusal))
    }

    /// The claims of a person an assertion vouches for, at any level: what a
    /// ticket is filed for, and read back for (W4.12). A filing with no
    /// assertion is the plugin as itself, which never files.
    fn vouched_person(
        &self,
        topic: &str,
        acting_for: Option<&CallerAssertion>,
        now_ns: i64,
    ) -> Result<CallerClaims, Status> {
        let refuse = |refusal: String| {
            self.note_refusal(&refusal);
            Err(Status::permission_denied(refusal))
        };
        let Some(assertion) = acting_for else {
            return refuse(if topic == FILE_TICKET {
                "a plugin files a ticket only for a person it acts for".to_string()
            } else {
                "a plugin reads what it filed only for a person it acts for".to_string()
            });
        };
        let verifier = self.verifier.as_ref().ok_or_else(|| {
            Status::unauthenticated(
                "this sidecar holds none of the dashboard's keys, so it can vouch for nobody",
            )
        })?;
        let claims = verifier
            .vouched(assertion, now_ns)
            .map_err(|refusal| Status::unauthenticated(refusal.said()))?;
        if !matches!(
            AccessLevel::try_from(claims.level),
            Ok(AccessLevel::Admin | AccessLevel::Write | AccessLevel::Read)
        ) {
            return refuse(format!(
                "{} holds no level on this plugin in this session, so nothing is sent for them",
                claims.subject
            ));
        }
        Ok(claims)
    }

    /// The claims of an admin of this plugin an assertion vouches for, in a
    /// session opened by Manage, or the refusal: the deployment's
    /// configuration is sent to only for one (W4.9, W6.4), and never by the
    /// plugin as itself.
    fn vouched_admin(
        &self,
        topic: &str,
        payload_type: &str,
        acting_for: Option<&CallerAssertion>,
        now_ns: i64,
    ) -> Result<(CallerClaims, Vec<String>), Status> {
        let refuse = |refusal: String| {
            self.note_refusal(&refusal);
            Err(Status::permission_denied(refusal))
        };
        let Some(assertion) = acting_for else {
            return refuse(format!(
                "{topic} is the deployment's configuration: a plugin sends it only acting for \
                 an admin of the plugin, and this carries no assertion"
            ));
        };
        let verifier = self.verifier.as_ref().ok_or_else(|| {
            Status::unauthenticated(
                "this sidecar holds none of the dashboard's keys, so it can vouch for nobody",
            )
        })?;
        let claims = verifier
            .vouched(assertion, now_ns)
            .map_err(|refusal| Status::unauthenticated(refusal.said()))?;
        if claims.level != AccessLevel::Admin as i32 {
            return refuse(format!(
                "{topic} is the deployment's configuration: a plugin sends it only acting for \
                 an admin of the plugin in a session opened by Manage, and {}'s is {}",
                claims.subject,
                session_named(claims.level)
            ));
        }
        // By `admin` on a role whose grants include it (W4.9, decisions/033
        // point 2): the link is custody's, and an admin of the plugin's other
        // roles alone is refused it, naming custody.
        let granting = self.roles_granting(topic);
        self.without_roles(&claims)?;
        if claims.roles.is_empty() {
            return Ok((claims, granting));
        }
        let admitted: Vec<String> = granting
            .iter()
            .filter(|role| {
                claims
                    .roles
                    .iter()
                    .any(|held| &held.role == *role && held.level == AccessLevel::Admin as i32)
            })
            .cloned()
            .collect();
        if admitted.is_empty() {
            return refuse(format!(
                "{} is {}, and {} holds {}",
                act_named(topic, payload_type),
                owned_by(&granting),
                who(&claims),
                held_on(&claims, &granting)
            ));
        }
        Ok((claims, admitted))
    }

    /// A link naming a new account, rather than an existing one, is a
    /// deployment admin's: creating an account stays theirs (W6.3, W6.4).
    fn names_a_new_account_only_for_a_deployment_admin(
        &self,
        link: &[u8],
        claims: &CallerClaims,
    ) -> Result<(), Status> {
        let link = LinkExternalAccountRequest::decode(link)
            .map_err(|failed| Status::internal(format!("the link did not read: {failed}")))?;
        if link.new_account_name.is_empty() || claims.deployment_admin {
            return Ok(());
        }
        let refusal = format!(
            "{} is an admin of this plugin and not a deployment admin: a link names an \
             existing account, and only a deployment admin names a new one",
            claims.subject
        );
        self.note_refusal(&refusal);
        Err(Status::permission_denied(refusal))
    }

    /// A link names an external account this plugin said its connection
    /// reaches (W2.8), or -- to remove it -- one it already links. Any other
    /// is refused before the conductor hears of it.
    async fn reported_by_this_plugin(&self, link: &[u8], now_ns: i64) -> Result<(), Status> {
        let link = LinkExternalAccountRequest::decode(link)
            .map_err(|failed| Status::internal(format!("the link did not read: {failed}")))?;
        let external = link.external_account_id.as_str();
        if self
            .reported
            .lock()
            .expect("reported lock poisoned")
            .contains(external)
        {
            return Ok(());
        }
        let unlinking = link.account_id.is_empty() && link.new_account_name.is_empty();
        if unlinking
            && self
                .configuration(now_ns)
                .await?
                .links
                .iter()
                .any(|held| held.external_account_id == external)
        {
            return Ok(());
        }
        let refusal = format!(
            "external account {external} is not one this plugin reported: a plugin links only \
             the accounts its connection reaches (W2.8)"
        );
        self.note_refusal(&refusal);
        Err(Status::permission_denied(refusal))
    }

    /// The person an assertion vouches for, if they may write `account`
    /// through this plugin -- or, for a command naming none, anything at all
    /// through it -- with the roles it is admitted under. Their access is
    /// what the dashboard signed, under a minute ago; a person narrows what a
    /// plugin may do and never widens it.
    ///
    /// **By the role holding the act** (contract v15, decisions/033 point 3,
    /// W4.9): the person holds `write` on one of the plugin's roles whose
    /// generated grants include the command's topic, with the account among
    /// that role's write accounts; a row several roles hold is admitted for
    /// `write` on any of them. Otherwise refused, naming each role that
    /// grants it and what the person holds on it.
    fn vouched_writer(
        &self,
        topic: &str,
        payload_type: &str,
        assertion: &CallerAssertion,
        account: Option<&str>,
        now_ns: i64,
    ) -> Result<(CallerClaims, Vec<String>), Status> {
        let verifier = self.verifier.as_ref().ok_or_else(|| {
            Status::unauthenticated(
                "this sidecar holds none of the dashboard's keys, so it can vouch for nobody",
            )
        })?;
        let claims = verifier
            .vouched(assertion, now_ns)
            .map_err(|refusal| Status::unauthenticated(refusal.said()))?;
        let refuse = |refusal: String| {
            self.note_refusal(&refusal);
            Err(Status::permission_denied(refusal))
        };
        // A command only in a session opened by Open: one under Manage
        // reaches no account's data, and one under View acts on nothing
        // (W6.9).
        if claims.level != AccessLevel::Write as i32 {
            return refuse(format!(
                "{} sent this in a {} session, and a command is sent for a person only in \
                 a session at write, opened by Open",
                claims.subject,
                session_named(claims.level)
            ));
        }
        let granting = self.roles_granting(topic);
        self.without_roles(&claims)?;
        if claims.roles.is_empty() {
            // One role, or none: the claims' write set is that role's, the
            // check before v15.
            let may_write = &claims.write_account_ids;
            return match account {
                Some(account) if !may_write.iter().any(|held| held == account) => {
                    Err(Status::permission_denied(format!(
                        "the person may not write account {account} through this plugin"
                    )))
                }
                None if may_write.is_empty() => Err(Status::permission_denied(
                    "the person may write nothing through this plugin",
                )),
                _ => Ok((claims, granting)),
            };
        }
        let mut admitted = Vec::new();
        let mut outside = Vec::new();
        for role in &granting {
            let Some(held) = claims
                .roles
                .iter()
                .find(|held| &held.role == role && held.level == AccessLevel::Write as i32)
            else {
                continue;
            };
            let writes: Vec<&str> = held
                .write_positions
                .iter()
                .filter_map(|at| claims.read_account_ids.get(*at as usize))
                .map(String::as_str)
                .collect();
            let reaches = match account {
                Some(account) => writes.contains(&account),
                None => !writes.is_empty(),
            };
            if reaches {
                admitted.push(role.clone());
            } else {
                outside.push(role.clone());
            }
        }
        if !admitted.is_empty() {
            return Ok((claims, admitted));
        }
        let act = act_named(topic, payload_type);
        if !outside.is_empty() {
            return refuse(match account {
                Some(account) => format!(
                    "{act} is {}, and {} holds write on {} without account {account}",
                    owned_by(&granting),
                    who(&claims),
                    outside.join(" and ")
                ),
                None => format!(
                    "{act} is {}, and {} may write no account on {}",
                    owned_by(&granting),
                    who(&claims),
                    outside.join(" and ")
                ),
            });
        }
        refuse(format!(
            "{act} is {}, and {} holds {}",
            owned_by(&granting),
            who(&claims),
            held_on(&claims, &granting)
        ))
    }
}

/// Who the claims name, for a refusal: their name where the dashboard gave
/// one, else their subject.
fn who(claims: &CallerClaims) -> &str {
    if claims.display_name.is_empty() {
        &claims.subject
    } else {
        &claims.display_name
    }
}

/// The act a topic carries, as the matrix names its operation: the request's
/// type less its package and `Request` (`RecordHoldingsStatement`), or the
/// topic where no type is given.
fn act_named<'a>(topic: &'a str, payload_type: &'a str) -> &'a str {
    payload_type
        .rsplit('.')
        .next()
        .and_then(|name| name.strip_suffix("Request"))
        .filter(|name| !name.is_empty())
        .unwrap_or(topic)
}

/// "custody's", "custody's and operations'", or no role's.
fn owned_by(roles: &[String]) -> String {
    if roles.is_empty() {
        return "no role's this plugin holds".into();
    }
    roles
        .iter()
        .map(|role| {
            if role.ends_with('s') {
                format!("{role}'")
            } else {
                format!("{role}'s")
            }
        })
        .collect::<Vec<_>>()
        .join(" and ")
}

/// What the claims hold on each of `roles`: "read on custody", "nothing on
/// operations".
fn held_on(claims: &CallerClaims, roles: &[String]) -> String {
    if roles.is_empty() {
        return "no role that grants it".into();
    }
    roles
        .iter()
        .map(|role| {
            match claims.roles.iter().find(|held| &held.role == role) {
                Some(held) => format!("{} on {role}", level_named(held.level)),
                None => format!("nothing on {role}"),
            }
        })
        .collect::<Vec<_>>()
        .join(" and ")
}

/// A session's level as a log names it.
pub(crate) fn level_named(level: i32) -> &'static str {
    match AccessLevel::try_from(level) {
        Ok(AccessLevel::Admin) => "admin",
        Ok(AccessLevel::Write) => "write",
        Ok(AccessLevel::Read) => "read",
        _ => "none",
    }
}

/// A session as the person chose it, for a refusal: by its button.
fn session_named(level: i32) -> &'static str {
    match AccessLevel::try_from(level) {
        Ok(AccessLevel::Admin) => "Manage (admin)",
        Ok(AccessLevel::Write) => "Open (write)",
        Ok(AccessLevel::Read) => "View (read)",
        _ => "level-less",
    }
}

/// A domain reply, read as the plugin-facing mirror it is on the wire.
#[allow(clippy::result_large_err)]
fn mirrored<R: Message + Default>(payload: Vec<u8>) -> Result<Response<R>, Status> {
    R::decode(payload.as_slice())
        .map(Response::new)
        .map_err(|failed| {
            Status::internal(format!("the reply did not read as its mirror: {failed}"))
        })
}

/// Where a refusal's reason code travels, beside its status.
pub const REFUSAL_METADATA: &str = "meridian-refusal-bin";

/// A refusal with its reason code from the catalogue beside the status.
pub(crate) fn refused_for(code: Code, words: String, reason: RefusalReason) -> Status {
    refused_naming(code, words, reason, Vec::new())
}

/// A refusal with its reason code and, for one naming what the command left
/// out, each field by its path (contract v9's REFUSAL_REASON_INCOMPLETE).
pub(crate) fn refused_naming(
    code: Code,
    words: String,
    reason: RefusalReason,
    fields: Vec<String>,
) -> Status {
    let mut metadata = MetadataMap::new();
    metadata.insert_bin(
        REFUSAL_METADATA,
        MetadataValue::from_bytes(
            &Refusal {
                reason: reason as i32,
                fields,
            }
            .encode_to_vec(),
        ),
    );
    Status::with_metadata(code, words, metadata)
}

pub(crate) fn refused(failed: BusError) -> Status {
    match failed {
        BusError::NoHandler(topic) => Status::unavailable(format!("nothing serves {topic}")),
        timeout @ BusError::Timeout { .. } => Status::deadline_exceeded(timeout.to_string()),
        // A component's refusal of its own (W9's book, contract v8), its
        // reason code carried beside the status and its words alone in it.
        // The fields it names as left out, where it names any, ride with it.
        BusError::HandlerFailed { detail, .. } => match meridian_bus::read_refusal(&detail)
            .and_then(|(reason, words)| Some((RefusalReason::try_from(reason).ok()?, words)))
        {
            // A store that could not check the command, nothing recorded:
            // to be tried again, so the status a caller retries (contract
            // v10). Every other refusal of a component's is `aborted`.
            Some((reason, words)) => refused_naming(
                if reason == RefusalReason::ReferenceUnavailable {
                    Code::Unavailable
                } else {
                    Code::Aborted
                },
                words.to_string(),
                reason,
                meridian_bus::refusal_fields(&detail),
            ),
            None => Status::aborted(detail),
        },
        BusError::NotPublishable(topic) => {
            Status::invalid_argument(format!("`{topic}` is not a publishable topic"))
        }
        other => Status::internal(other.to_string()),
    }
}

#[cfg(test)]
mod tests;
