//! The typed operations' hand-written half (spec/typed-sidecar-operations).
//!
//! `operations.rs` is generated by meridian-design, one method per operation,
//! and each calls into this: read the plugin's params as the domain message,
//! stamp what only the sidecar knows, check the grant, send. This is the part
//! that does not vary by operation, which is why it is written once and the
//! part that does is generated.
//!
//! A refusal is the call's gRPC status, chosen by what the caller should do
//! about it: `permission_denied` for a topic none of the plugin's roles
//! grants, `failed_precondition` for an external account nobody has linked,
//! `unavailable` when nothing serves the topic, `deadline_exceeded` when it
//! did not answer in time, `aborted` when it answered with a refusal.

use meridian_bus::BusError;
use meridian_pb::plugin::v1 as plugin;
use meridian_pb::v1::CallerAssertion;
use prost::Message;
use tonic::{Response, Status};

use crate::service::Sidecar;

// The tonic surface already returns `Result<_, Status>` everywhere; boxing the
// error here alone would buy nothing.
#[allow(clippy::result_large_err)]
impl Sidecar {
    pub(crate) fn instance_id(&self) -> &str {
        &self.identity.instance_id
    }

    /// A plugin's params, read as the domain message they are on the wire.
    ///
    /// The params keep every field number of the domain message and drop only
    /// the stamped ones, so their encoding is the domain message's with those
    /// unset. Refused before registration, as every operation is.
    pub(crate) fn as_domain<P: Message, D: Message + Default>(
        &self,
        params: P,
    ) -> Result<D, Status> {
        self.admitted()?;
        D::decode(params.encode_to_vec().as_slice()).map_err(|failed| {
            Status::internal(format!(
                "the params did not read as the domain message: {failed}"
            ))
        })
    }

    /// The topic this instance sends on: its own identifier where the row
    /// names `{instance}`, so a plugin can speak only as itself.
    fn own_topic(&self, topic: &str) -> String {
        topic.replace("{instance}", self.instance_id())
    }

    fn granted(&self, topic: &str) -> Result<(), Status> {
        let registration = self.admitted()?;
        if registration.grants.may_publish(topic) {
            return Ok(());
        }
        let held = if registration.roles.is_empty() {
            "no role".to_string()
        } else {
            registration.roles.join(", ")
        };
        let refusal = format!("no grant for {topic}: this plugin holds {held}");
        self.note_refusal(&refusal);
        Err(Status::permission_denied(refusal))
    }

    /// An event: checked, published, and its identifier handed back.
    pub(crate) async fn publish_typed<D: Message>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
    ) -> Result<Response<plugin::Published>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let message_id = self
            .bus
            .publish(&topic, payload_type, message.encode_to_vec(), None, None)
            .map_err(refused)?;
        Ok(Response::new(plugin::Published { message_id }))
    }

    /// A command or a query: checked, asked, and the domain reply handed back
    /// as its plugin-facing mirror, which it is on the wire.
    pub(crate) async fn call_typed<D: Message, R: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
    ) -> Result<Response<R>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let (_, payload) = self
            .bus
            .call(&topic, payload_type, message.encode_to_vec(), None, None)
            .await
            .map_err(refused)?;
        R::decode(payload.as_slice())
            .map(Response::new)
            .map_err(|failed| {
                Status::internal(format!("the reply did not read as its mirror: {failed}"))
            })
    }

    /// A command: checked against the grant, against the plugin's write scope
    /// for the account it names, and -- when it is sent for a person (W4.9) --
    /// against what the dashboard vouched that person may write; then asked,
    /// with the person stamped on the envelope.
    pub(crate) async fn command_typed<D: Message, R: Message + Default>(
        &self,
        topic: &str,
        payload_type: &str,
        message: D,
        account: Option<String>,
        acting_for: Option<CallerAssertion>,
    ) -> Result<Response<R>, Status> {
        let topic = self.own_topic(topic);
        self.granted(&topic)?;
        let now = now_ns();
        if let Some(account) = &account {
            let configuration = self.configuration(now).await?;
            if !configuration.write_account_ids.contains(account) {
                let refusal = format!(
                    "account {account} is outside this plugin's write scope: nobody may write \
                     it through this plugin"
                );
                self.note_refusal(&refusal);
                return Err(Status::permission_denied(refusal));
            }
        }
        let subject = match acting_for {
            None => String::new(),
            Some(assertion) => self.vouched_writer(&assertion, account.as_deref(), now)?,
        };
        let (_, payload) = self
            .bus
            .call_for(
                &topic,
                payload_type,
                message.encode_to_vec(),
                None,
                None,
                &subject,
            )
            .await
            .map_err(refused)?;
        R::decode(payload.as_slice())
            .map(Response::new)
            .map_err(|failed| {
                Status::internal(format!("the reply did not read as its mirror: {failed}"))
            })
    }

    /// The person an assertion vouches for, if they may write `account`
    /// through this plugin -- or, for a command naming none, anything at all
    /// through it. Their access is what the dashboard signed, under a minute
    /// ago; a person narrows what a plugin may do and never widens it.
    fn vouched_writer(
        &self,
        assertion: &CallerAssertion,
        account: Option<&str>,
        now_ns: i64,
    ) -> Result<String, Status> {
        let verifier = self.verifier.as_ref().ok_or_else(|| {
            Status::unauthenticated(
                "this sidecar holds none of the dashboard's keys, so it can vouch for nobody",
            )
        })?;
        let claims = verifier
            .vouched(assertion, now_ns)
            .map_err(|refusal| Status::unauthenticated(refusal.said()))?;
        let may_write: std::collections::BTreeSet<&String> = claims
            .access
            .iter()
            .flat_map(|held| &held.write_account_ids)
            .collect();
        match account {
            Some(account) if !may_write.iter().any(|held| *held == account) => {
                Err(Status::permission_denied(format!(
                    "the person may not write account {account} through this plugin"
                )))
            }
            None if may_write.is_empty() => Err(Status::permission_denied(
                "the person may write nothing through this plugin",
            )),
            _ => Ok(claims.subject),
        }
    }
}

pub(crate) fn now_ns() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as i64)
        .unwrap_or(0)
}

pub(crate) fn refused(failed: BusError) -> Status {
    match failed {
        BusError::NoHandler(topic) => Status::unavailable(format!("nothing serves {topic}")),
        timeout @ BusError::Timeout { .. } => Status::deadline_exceeded(timeout.to_string()),
        BusError::HandlerFailed { detail, .. } => Status::aborted(detail),
        BusError::NotPublishable(topic) => {
            Status::invalid_argument(format!("`{topic}` is not a publishable topic"))
        }
        other => Status::internal(other.to_string()),
    }
}

#[cfg(test)]
mod tests;
