//! What the wizard asks for, tested and then applied.
//!
//! Two questions and one command, all from the dashboard (W7.4, W7.5):
//!
//! - the sealing key, which every credential after it is sealed to;
//! - a check: does this answer work, and if not what is wrong with it;
//! - apply: write it all, in one order, idempotently, and then give up the
//!   rights that did the writing.
//!
//! A check never writes. That is worth stating because one of the answers is
//! "create Zitadel's database with this privileged connection", and the
//! difference between testing that and doing it is the difference between a
//! wizard somebody can back out of and one they cannot
//! (spec/installation-and-first-run, requirement 14).

use std::collections::BTreeMap;

use meridian_domain::v1::{
    administrator_answer::Named, bundled_zitadel_answer::Directory,
    first_run_check_request::Answer, login_backend_answer::Backend, AddressesAnswer,
    AdministratorAnswer, BroughtDatabase, DatabaseLogin, FirstRunApplied, FirstRunCheckReply,
    FirstRunCheckRequest, FirstRunConfiguration, LoginBackendAnswer, RuntimeDatabaseAnswer,
};

use crate::cluster::{Cluster, Workload};

/// How long a database that was at zero replicas gets to accept a connection.
///
/// A pod to schedule, an image to pull and an initdb to run. Generous, because
/// the alternative is a wizard somebody has to press twice and a deployment
/// half configured in between.
const STARTING: std::time::Duration = std::time::Duration::from_secs(180);

/// What the wizard asked for, or what it would have asked for.
///
/// These names are the administrator's to choose and almost nobody will. A
/// blank answer is a default rather than a refusal: refusing here would be a
/// deployment that cannot be brought up over a name nobody cared about.
fn database_or(named: &str, fallback: &str) -> String {
    match named.trim().is_empty() {
        true => fallback.to_string(),
        false => named.trim().to_string(),
    }
}

fn role_or(named: &str, fallback: &str) -> String {
    database_or(named, fallback)
}
use crate::sealing::SealingKey;

/// The names the chart gives what this writes. Passed in rather than built
/// here, because they are the release's and the Role names the same ones: a
/// name this did not get from the chart is a name RBAC would refuse anyway.
#[derive(Debug, Clone)]
pub struct Names {
    pub database_secret: String,
    pub dashboard_oidc_secret: String,
    pub ldap_bind_secret: String,
    /// Where a browser reaches this deployment, which the components read
    /// rather than take from a values file nobody edited.
    pub addresses_secret: String,
    pub own_binding: String,
    /// Restarted after the Secrets are written, in this order.
    pub restart: Vec<String>,
}

/// The Postgres this chart can bring, as the Job knows it.
///
/// Its passwords are generated by the chart and read from this Job's own
/// environment: nobody types them, nobody is shown them, and they never cross
/// the bus, so unlike every other credential here there is nothing to seal.
///
/// Absent when the chart renders no database, and then choosing to bring one
/// is refused rather than half-done.
#[derive(Debug, Clone)]
pub struct BroughtServer {
    /// The StatefulSet to scale up. At zero it has no claim and no disk.
    pub workload: String,
    pub host: String,
    pub port: u32,
    pub superuser: String,
    pub superuser_password: String,
    pub serving_password: String,
    pub migrating_password: String,
}

pub struct FirstRun {
    pub key: SealingKey,
    pub names: Names,
    pub cluster: Box<dyn Cluster>,
    /// Tests a Postgres login, returning what is wrong with it. Injected so
    /// this crate's tests need no database and the real one needs no mock.
    pub probe: Box<dyn DatabaseProbe>,
    /// Makes a database and its roles, for the routes that bring one.
    pub provisioner: Box<dyn Provisioner>,
    /// The database this chart can bring, when it renders one.
    pub brought: Option<BroughtServer>,
}

/// A database and the roles that will live in it, made once.
///
/// Built here and carried out by a `Provisioner`, so this crate's tests need
/// no Postgres and the real one needs no mock.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Provision {
    pub database: String,
    pub roles: Vec<NewRole>,
}

/// A login role to make, and what it may do to the schema once it exists.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewRole {
    pub name: String,
    pub password: String,
    /// Whether it may create tables. The migrating role may; the serving role
    /// must not, because a serving role that can migrate a customer's
    /// database by restarting is the finding this wizard exists to make
    /// impossible.
    pub may_create: bool,
    /// Whether it owns the database, which is what a component that runs its
    /// own migrations needs -- Zitadel does, and the runtime's roles do not.
    pub owns_database: bool,
}

/// Makes a database and its roles, with a privileged connection used once.
///
/// Named as its own capability rather than folded into the probe, because the
/// two differ in exactly the way requirement 14 cares about: a check connects
/// and reports, and this writes.
pub trait Provisioner: Send + Sync {
    /// Idempotent: a database or a role that is already there is left as it
    /// is, except for the password, which is set so that a second apply with
    /// a regenerated one still leaves a deployment that can connect.
    fn provision(
        &self,
        privileged: &DatabaseLogin,
        password: &[u8],
        plan: &Provision,
    ) -> Result<(), String>;
}

/// What a database answer is checked against.
pub trait DatabaseProbe: Send + Sync {
    /// Connect as this login and report the findings: empty is a pass.
    ///
    /// `may_create` is what the role is expected to be able to do. The
    /// migrating role may create a table and the serving role may not, and
    /// a serving role that may is the finding worth having: it is the one
    /// that turns a restart into a migration.
    fn check(&self, login: &DatabaseLogin, password: &[u8], may_create: bool) -> Vec<String>;
}

impl FirstRun {
    /// Whether somebody has already been through the wizard.
    ///
    /// Asked once at start. A deployment that has been configured has no work
    /// for this Job, and a Job with no work gives up its rights rather than
    /// waiting with them (decisions/016).
    pub async fn already_configured(&self) -> Result<bool, String> {
        self.cluster
            .secret_has_key(&self.names.database_secret, "url")
            .await
            .map_err(|failed| failed.to_string())
    }

    /// Give up the rights without applying anything, for a Job that found its
    /// work already done.
    pub async fn stand_down(&self) -> Result<(), String> {
        self.cluster
            .drop_own_rights(&self.names.own_binding)
            .await
            .map_err(|failed| failed.to_string())
    }

    /// W7.4. Test one answer, writing nothing.
    pub fn check(&self, request: &FirstRunCheckRequest) -> FirstRunCheckReply {
        let findings = match &request.answer {
            Some(Answer::RuntimeDatabase(database)) => self.check_database(database),
            Some(Answer::LoginBackend(backend)) => self.check_backend(backend),
            Some(Answer::Addresses(addresses)) => check_addresses(addresses),
            Some(Answer::Administrator(administrator)) => check_administrator(administrator),
            None => vec!["nothing to check".into()],
        };
        FirstRunCheckReply {
            passed: findings.is_empty(),
            findings,
        }
    }

    fn check_database(&self, database: &RuntimeDatabaseAnswer) -> Vec<String> {
        // Nothing to connect to yet. The database this chart brings does not
        // exist until applying starts it, and the roles do not exist until
        // applying makes them, so there is no login here to test and no
        // finding to give. What can be checked is that the deployment has one
        // to bring at all: choosing it on a chart that rendered none would
        // otherwise pass here and fail at the only step that writes.
        if database.brought.is_some() {
            return match self.brought.is_some() {
                true => Vec::new(),
                false => vec![
                    "this deployment was installed with no database to bring. Point at one \
                     you run, or reinstall with the chart's own database enabled."
                        .into(),
                ],
            };
        }

        let mut findings = Vec::new();
        for (login, may_create, what) in [
            (&database.serving, false, "serving"),
            (&database.migrating, true, "migrating"),
        ] {
            let Some(login) = login else {
                findings.push(format!("no {what} login"));
                continue;
            };
            match self.open_password(login, &format!("runtime_database.{what}.password")) {
                Err(refusal) => findings.push(refusal),
                Ok(password) => findings.extend(self.probe.check(login, &password, may_create)),
            }
        }
        findings
    }

    fn check_backend(&self, backend: &LoginBackendAnswer) -> Vec<String> {
        match &backend.backend {
            // Where the firm has no directory at all, this deployment holds
            // the account (decisions/018) and there is nothing here to
            // check: the wizard asked for a login and a password, the Job
            // hashes the password, and the dashboard makes the account.
            Some(Backend::Bundled(_)) => Vec::new(),
            Some(Backend::Oidc(oidc)) => {
                let mut findings = Vec::new();
                if oidc.issuer.trim().is_empty() {
                    findings.push("no issuer".into());
                }
                if oidc.client_id.trim().is_empty() {
                    findings.push("no client id".into());
                }
                findings
            }
            None => vec!["no login backend chosen".into()],
        }
    }

    fn open_password(&self, login: &DatabaseLogin, field: &str) -> Result<Vec<u8>, String> {
        let Some(sealed) = &login.password else {
            return Err(format!("no password for {field}"));
        };
        self.key.open(sealed, field)
    }

    /// W7.5. Write everything, in one order, and give up the rights.
    ///
    /// Idempotent at every step, so applying the same configuration again
    /// completes a partial one: that is what makes a failed apply something
    /// an administrator can retry rather than a deployment to rebuild.
    pub async fn apply(&self, configuration: &FirstRunConfiguration) -> FirstRunApplied {
        let mut steps: Vec<String> = Vec::new();
        let mut applied = FirstRunApplied::default();

        // Tested again here, because a test and an apply are separate moments
        // and what was true at the first may not be at the second: a password
        // rotated between them, a role's rights changed. Writing a
        // configuration that no longer works would leave a deployment with a
        // database it cannot reach and no wizard to fix it in.
        for answer in [
            configuration
                .runtime_database
                .clone()
                .map(Answer::RuntimeDatabase),
            configuration
                .login_backend
                .clone()
                .map(Answer::LoginBackend),
            // Named rather than optional: a configuration that names no
            // administrator produces a deployment nobody can administer,
            // which is recovered only with a claim code from the platform
            // (decisions/017). Refusing it costs a sentence now and saves an
            // afternoon after the components have restarted.
            Some(Answer::Administrator(
                configuration.administrator.clone().unwrap_or_default(),
            )),
        ]
        .into_iter()
        .flatten()
        {
            let checked = self.check(&FirstRunCheckRequest {
                answer: Some(answer),
            });
            if !checked.passed {
                applied.refusal_reason = checked.findings.join("; ");
                return applied;
            }
        }

        if let Err(refusal) = self.write_database(configuration).await {
            applied.steps = steps;
            applied.refusal_reason = refusal;
            return applied;
        }
        steps.push("secrets".into());

        if let Err(refusal) = self.write_identity(configuration).await {
            applied.steps = steps;
            applied.refusal_reason = refusal;
            return applied;
        }
        steps.push("identity".into());

        if let Err(refusal) = self.write_addresses(configuration).await {
            applied.steps = steps;
            applied.refusal_reason = refusal;
            return applied;
        }
        steps.push("addresses".into());

        if let Err(refusal) = self.roll(configuration).await {
            applied.steps = steps;
            applied.refusal_reason = refusal;
            return applied;
        }
        steps.push("restart".into());

        // Last, and only after every step succeeded: a Job that gave these up
        // early could not finish, and one that never gives them up leaves a
        // right in the deployment that nothing needs (decisions/016).
        match self.cluster.drop_own_rights(&self.names.own_binding).await {
            Ok(()) => {
                steps.push("rights released".into());
                applied.rights_released = true;
            }
            Err(failed) => {
                applied.steps = steps;
                applied.refusal_reason = format!("the rights could not be given up: {failed}");
                return applied;
            }
        }

        applied.applied = true;
        applied.steps = steps;
        applied
    }

    /// Start the database this chart brings, and make what lives in it.
    ///
    /// Scaling rather than creating: the StatefulSet is rendered at zero, so
    /// its claim does not exist until this scales it and the StatefulSet
    /// controller makes one. Nothing in the deployment creates a resource in
    /// its own cluster (decisions/016).
    ///
    /// Idempotent like every other step. A second apply scales an already
    /// running database to one, finds the databases and roles there, and sets
    /// the passwords and grants again.
    async fn start_brought_database(
        &self,
        brought: &BroughtDatabase,
    ) -> Result<DatabaseLogin, String> {
        let server = self
            .brought
            .as_ref()
            .ok_or("this deployment was installed with no database to bring")?;

        self.cluster
            .scale(Workload::StatefulSet, &server.workload, 1)
            .await
            .map_err(|failed| format!("the database could not be started: {failed}"))?;

        let privileged = DatabaseLogin {
            host: server.host.clone(),
            port: server.port,
            database: "postgres".into(),
            role: server.superuser.clone(),
            password: None,
            // In the cluster, on a network policy that admits this deployment
            // and nothing else. A certificate would be a certificate somebody
            // has to rotate for a database nobody reaches from outside.
            ssl_mode: "disable".into(),
        };

        // A database that was at zero replicas a moment ago is a pod being
        // scheduled, an image being pulled and an initdb running. Waiting here
        // rather than failing is the difference between a wizard that works
        // and one somebody has to press twice.
        let plan = Provision {
            database: database_or(&brought.database, "meridian"),
            roles: vec![
                NewRole {
                    name: role_or(&brought.serving_role, "meridian_app"),
                    password: server.serving_password.clone(),
                    may_create: false,
                    owns_database: false,
                },
                NewRole {
                    name: role_or(&brought.migrating_role, "meridian_migrate"),
                    password: server.migrating_password.clone(),
                    may_create: true,
                    owns_database: false,
                },
            ],
        };
        self.provision_when_ready(&privileged, server.superuser_password.as_bytes(), &plan)?;

        Ok(privileged)
    }

    /// Provision, retrying while the server is still starting.
    ///
    /// Only a connection failure is retried. A refusal from a server that
    /// answered -- a name that is not a name, a role that cannot be made -- is
    /// returned at once, because waiting will not change it.
    fn provision_when_ready(
        &self,
        privileged: &DatabaseLogin,
        password: &[u8],
        plan: &Provision,
    ) -> Result<(), String> {
        let deadline = std::time::Instant::now() + STARTING;
        loop {
            match self.provisioner.provision(privileged, password, plan) {
                Ok(()) => return Ok(()),
                Err(failed) if failed.contains("could not connect") => {
                    if std::time::Instant::now() >= deadline {
                        return Err(format!(
                            "the database did not accept a connection within {}s: {failed}",
                            STARTING.as_secs()
                        ));
                    }
                    std::thread::sleep(std::time::Duration::from_secs(2));
                }
                Err(failed) => return Err(failed),
            }
        }
    }

    async fn write_database(&self, configuration: &FirstRunConfiguration) -> Result<(), String> {
        let Some(database) = &configuration.runtime_database else {
            return Err("no database in this configuration".into());
        };

        // The route that brings one: start it, make the database and the two
        // roles, and write the URLs the components read. Nothing was typed and
        // nothing was sealed, because these passwords were generated in the
        // cluster and never left it.
        if let Some(brought) = &database.brought {
            let privileged = self.start_brought_database(brought).await?;
            let server = self.brought.as_ref().expect("checked while starting");
            let inside = |role: &str, password: &str| {
                url_for(
                    &DatabaseLogin {
                        host: privileged.host.clone(),
                        port: privileged.port,
                        database: database_or(&brought.database, "meridian"),
                        role: role.to_string(),
                        password: None,
                        ssl_mode: privileged.ssl_mode.clone(),
                    },
                    password.as_bytes(),
                )
            };

            let values = BTreeMap::from([
                (
                    "url".to_string(),
                    inside(
                        &role_or(&brought.serving_role, "meridian_app"),
                        &server.serving_password,
                    )
                    .into_bytes(),
                ),
                (
                    "migrate-url".to_string(),
                    inside(
                        &role_or(&brought.migrating_role, "meridian_migrate"),
                        &server.migrating_password,
                    )
                    .into_bytes(),
                ),
            ]);

            return self
                .cluster
                .put_secret(&self.names.database_secret, &values)
                .await
                .map_err(|failed| failed.to_string());
        }

        let serving = database
            .serving
            .as_ref()
            .ok_or("no serving login".to_string())?;
        let migrating = database
            .migrating
            .as_ref()
            .ok_or("no migrating login".to_string())?;

        let values = BTreeMap::from([
            (
                "url".to_string(),
                url_for(
                    serving,
                    &self.open_password(serving, "runtime_database.serving.password")?,
                )
                .into_bytes(),
            ),
            (
                "migrate-url".to_string(),
                url_for(
                    migrating,
                    &self.open_password(migrating, "runtime_database.migrating.password")?,
                )
                .into_bytes(),
            ),
        ]);

        self.cluster
            .put_secret(&self.names.database_secret, &values)
            .await
            .map_err(|failed| failed.to_string())
    }

    async fn write_identity(&self, configuration: &FirstRunConfiguration) -> Result<(), String> {
        let Some(backend) = configuration
            .login_backend
            .as_ref()
            .and_then(|b| b.backend.as_ref())
        else {
            return Err("no login backend in this configuration".into());
        };

        match backend {
            Backend::Bundled(bundled) => {
                // On the route that brings a database, Zitadel's lives on the
                if let Some(meridian_domain::v1::bundled_zitadel_answer::Directory::Ldap(ldap)) =
                    &bundled.directory
                {
                    let password = ldap
                        .bind_password
                        .as_ref()
                        .ok_or("no LDAP bind password".to_string())
                        .and_then(|sealed| self.key.open(sealed, "ldap.bind_password"))?;
                    // The whole connection, not only the password. The
                    // dashboard binds to this directory itself now
                    // (decisions/018), so what it needs is where the servers
                    // are and how a person is found in them -- which the
                    // wizard has always asked for and which used to be
                    // configured into something else.
                    let mut values = BTreeMap::from([
                        ("password".to_string(), password),
                        ("servers".to_string(), ldap.servers.join(",").into_bytes()),
                        ("base-dn".to_string(), ldap.base_dn.clone().into_bytes()),
                        ("bind-dn".to_string(), ldap.bind_dn.clone().into_bytes()),
                    ]);
                    // `{}` is where the name somebody typed goes, escaped.
                    // A firm that said nothing gets the common case rather
                    // than a filter that matches nobody.
                    let filter = match ldap.user_filter.trim() {
                        "" => "(uid={})".to_string(),
                        given => given.to_string(),
                    };
                    values.insert("user-filter".to_string(), filter.into_bytes());
                    self.cluster
                        .put_secret(&self.names.ldap_bind_secret, &values)
                        .await
                        .map_err(|failed| failed.to_string())?;
                }
                Ok(())
            }
            Backend::Oidc(oidc) => {
                // The firm's own directory: the bundle is not used, so it is
                // left at zero replicas rather than waiting forever for a
                // database nobody is going to configure.
                let mut values = BTreeMap::from([
                    ("issuer".to_string(), oidc.issuer.clone().into_bytes()),
                    ("client-id".to_string(), oidc.client_id.clone().into_bytes()),
                ]);
                if let Some(sealed) = &oidc.client_secret {
                    values.insert(
                        "client-secret".to_string(),
                        self.key.open(sealed, "oidc.client_secret")?,
                    );
                }
                // Absent means the dashboard's own default, `groups`, which is
                // what Entra ID, Okta and Zitadel use. Written only when the
                // wizard was told something else, so a firm whose provider
                // names the claim differently can say so.
                if !oidc.groups_claim.trim().is_empty() {
                    values.insert(
                        "groups-claim".to_string(),
                        oidc.groups_claim.trim().as_bytes().to_vec(),
                    );
                }
                self.cluster
                    .put_secret(&self.names.dashboard_oidc_secret, &values)
                    .await
                    .map_err(|failed| failed.to_string())?;

                Ok(())
            }
        }
    }

    /// The account this deployment holds, if that is the branch chosen.
    fn local_account<'a>(
        &self,
        configuration: &'a FirstRunConfiguration,
    ) -> Option<&'a meridian_domain::v1::LocalAccountAnswer> {
        match configuration.login_backend.as_ref()?.backend.as_ref()? {
            Backend::Bundled(bundled) => match bundled.directory.as_ref()? {
                Directory::LocalAccount(account) => Some(account),
                _ => None,
            },
            _ => None,
        }
    }

    /// Where a browser reaches this deployment, as the components read it.
    ///
    /// Written rather than rendered, because the wizard is what learns it: a
    /// chart value would be a second place the same fact lives, and the one
    /// nobody edited would win on the next upgrade.
    ///
    /// Zitadel is told the same thing in its own vocabulary, because it puts
    /// its own address in every token it issues, and the dashboard checks that
    /// against the issuer it was told to expect.
    async fn write_addresses(&self, configuration: &FirstRunConfiguration) -> Result<(), String> {
        let Some(addresses) = &configuration.addresses else {
            return Ok(());
        };

        let mut values = BTreeMap::from([(
            "dashboard-url".to_string(),
            addresses.dashboard_url.clone().into_bytes(),
        )]);

        // The first administrator's account, where this deployment holds it
        // (decisions/018). The wizard sealed a password to this Job; the Job
        // hashes it and writes only the hash, so the password stops here and
        // no component reads one.
        //
        // Collected and discarded until 2026-09-24: the wizard sealed a login,
        // an email, a name and a password into `LocalAccountAnswer` and
        // nothing opened it, so that branch produced a deployment holding an
        // administrator's permission and no account to sign in as. The e2e
        // did not catch it because it asserted the permission, which was
        // written, rather than a sign-in, which was impossible.
        if let Some(account) = self.local_account(configuration) {
            let password = self.key.open(
                account
                    .initial_password
                    .as_ref()
                    .ok_or("no password for the first administrator's account")?,
                "local_account.initial_password",
            )?;
            let hashed = hash_password(&String::from_utf8_lossy(&password))?;
            // What turns the dashboard's accounts on. Its own key rather than
            // the hash's presence, because the hash only seeds the first
            // account: an operator who removes it afterwards must not turn a
            // configured deployment back into one serving its wizard.
            values.insert("local-accounts".to_string(), b"on".to_vec());
            values.insert(
                "administrator-password-hash".to_string(),
                hashed.into_bytes(),
            );
            // Two keys for two readers. The account's name is what the
            // dashboard makes it under; the login is what the conductor's
            // permission names, and it is the name as the dashboard will sign
            // them in. One key serving both gave the administrator a
            // permission for a login nobody signs in as.
            if !account.login_name.trim().is_empty() {
                values.insert(
                    "local-account-name".to_string(),
                    account.login_name.trim().to_lowercase().into_bytes(),
                );
                values.insert(
                    "administrator-login".to_string(),
                    meridian_access::local_login(&account.login_name).into_bytes(),
                );
            }
            if !account.given_name.trim().is_empty() {
                values.insert(
                    "administrator-display-name".to_string(),
                    format!(
                        "{} {}",
                        account.given_name.trim(),
                        account.family_name.trim()
                    )
                    .trim()
                    .as_bytes()
                    .to_vec(),
                );
            }
        }

        // W7.5 records who administers this deployment; W7.6 writes the
        // permission. Here rather than in a Secret of its own because this is
        // already the one the wizard fills with things the components read,
        // and the Job may write no Secret the chart has not named.
        if let Some(administrator) = &configuration.administrator {
            match &administrator.named {
                Some(Named::DirectoryGroup(group)) if !group.trim().is_empty() => {
                    values.insert(
                        "administrator-directory-group".to_string(),
                        group.trim().as_bytes().to_vec(),
                    );
                }
                Some(Named::LocalAccountLogin(login)) if !login.trim().is_empty() => {
                    // In the form the dashboard signs this person in as, where
                    // the account is this deployment's; as given where it is
                    // somebody else's, whose form this does not know.
                    let login = match self.local_account(configuration) {
                        Some(_) => meridian_access::local_login(login),
                        None => login.trim().to_string(),
                    };
                    values.insert("administrator-login".to_string(), login.into_bytes());
                }
                _ => {}
            }
        }

        if !addresses.zitadel_url.trim().is_empty() {
            let (domain, port, secure) = split_zitadel_url(&addresses.zitadel_url)?;
            values.extend([
                (
                    "issuer".to_string(),
                    addresses
                        .zitadel_url
                        .trim_end_matches('/')
                        .as_bytes()
                        .to_vec(),
                ),
                ("zitadel-external-domain".to_string(), domain.into_bytes()),
                ("zitadel-external-port".to_string(), port.into_bytes()),
                ("zitadel-external-secure".to_string(), secure.into_bytes()),
            ]);
        }

        // Whoever signs people in, whichever route was chosen. The dashboard
        // reads one issuer, from this Secret: on the bundled route it is
        // Zitadel's own address, written just above from the address the
        // wizard gave it. On the firm's own directory it is theirs, and until
        // 2026-09-23 it was written only into the dashboard's OIDC Secret,
        // which the chart reads the client id out of and not the issuer. A
        // deployment installed with the bundle rendered and then pointed at
        // the firm's directory therefore came up with no issuer at all, and
        // nobody could sign in. That is the combination somebody installing
        // from the runbook hits, because rendering the bundle is what keeps
        // the choice open until the wizard.
        if let Some(Backend::Oidc(oidc)) = configuration
            .login_backend
            .as_ref()
            .and_then(|backend| backend.backend.as_ref())
        {
            if !oidc.issuer.trim().is_empty() {
                values.insert(
                    "issuer".to_string(),
                    oidc.issuer.trim().trim_end_matches('/').as_bytes().to_vec(),
                );
            }
        }

        self.cluster
            .put_secret(&self.names.addresses_secret, &values)
            .await
            .map_err(|failed| failed.to_string())
    }

    async fn roll(&self, _configuration: &FirstRunConfiguration) -> Result<(), String> {
        for name in &self.names.restart {
            self.cluster
                .restart(name)
                .await
                .map_err(|failed| failed.to_string())?;
        }
        Ok(())
    }
}

/// Zitadel's address, in the three parts Zitadel itself is configured with.
///
/// It states its own address in every token it issues, and the dashboard
/// checks that against the issuer it expects. One answer in the wizard, and
/// both sides told the same thing, rather than a values file and a Secret
/// that agree until somebody edits one.
fn split_zitadel_url(url: &str) -> Result<(String, String, String), String> {
    let (scheme, rest) = url
        .trim()
        .split_once("://")
        .ok_or_else(|| format!("{url} is not a URL"))?;
    let rest = rest.trim_end_matches('/');
    let secure = scheme == "https";
    let (host, port) = match rest.split_once(':') {
        Some((host, port)) => (host, port.to_string()),
        None if secure => (rest, "443".to_string()),
        None => (rest, "80".to_string()),
    };
    if host.is_empty() {
        return Err(format!("{url} names no host"));
    }
    Ok((host.to_string(), port, secure.to_string()))
}

/// A Postgres URL, with the password escaped rather than pasted.
fn url_for(login: &DatabaseLogin, password: &[u8]) -> String {
    let password = String::from_utf8_lossy(password);
    let ssl_mode = if login.ssl_mode.trim().is_empty() {
        "verify-full"
    } else {
        login.ssl_mode.trim()
    };
    format!(
        "postgres://{}:{}@{}:{}/{}?sslmode={ssl_mode}",
        encode(&login.role),
        encode(&password),
        login.host,
        if login.port == 0 { 5432 } else { login.port },
        login.database
    )
}

/// Percent-encoding for the two fields that are a person's to choose. A
/// password with an `@` in it otherwise makes a URL that names another host.
fn encode(value: &str) -> String {
    value
        .bytes()
        .map(|byte| match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' => {
                (byte as char).to_string()
            }
            other => format!("%{other:02X}"),
        })
        .collect()
}

/// W7.4. Whether anybody will be able to administer this deployment.
///
/// Shape only, and that is the whole of what can be checked here. Asking a
/// directory whether a group exists is not done for any backend, and the
/// wizard says so on the page rather than implying otherwise: nothing in the
/// deployment speaks LDAP, the bundled Zitadel has no database until this
/// very configuration is applied, and a firm's own provider asserts a
/// person's groups inside their own token rather than listing a directory's
/// (spec/installation-and-first-run, requirement 13).
///
/// What is caught here is the case worth catching without a directory: nobody
/// named. That produces a configured deployment with no administrator, which
/// is recovered only with a claim code from the platform, and it is far
/// cheaper to refuse now than to discover after the components have restarted.
fn check_administrator(administrator: &AdministratorAnswer) -> Vec<String> {
    let named = |what: &str, value: &String| match value.trim().is_empty() {
        true => vec![format!(
            "the {what} naming this deployment's administrators is empty, so nobody would \
             administer it"
        )],
        false => Vec::new(),
    };

    match &administrator.named {
        Some(Named::DirectoryGroup(group)) => named("directory group", group),
        Some(Named::LocalAccountLogin(login)) => named("login", login),
        None => vec![
            "nobody is named to administer this deployment. Name a directory group whose \
             members administer it, or the local account being created."
                .into(),
        ],
    }
}

fn check_addresses(addresses: &AddressesAnswer) -> Vec<String> {
    let mut findings = Vec::new();
    if addresses.dashboard_url.trim().is_empty() {
        findings.push("no address for the dashboard: the directory sends people back to it".into());
    }
    findings
}

#[cfg(test)]
#[path = "service/tests.rs"]
mod tests;

/// Argon2id, PHC string form, with a fresh salt.
///
/// Here rather than in the dashboard because this is where the password is
/// opened: the Job holds the only key that can read what the wizard sealed,
/// and the hash is what leaves. Verified in the dashboard, which is where the
/// accounts are kept (decisions/018).
fn hash_password(password: &str) -> Result<String, String> {
    use argon2::password_hash::{rand_core::OsRng, PasswordHasher, SaltString};
    let salt = SaltString::generate(&mut OsRng);
    argon2::Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map(|hash| hash.to_string())
        .map_err(|failed| format!("the administrator's password could not be hashed: {failed}"))
}
