#!/usr/bin/env python3
"""Broker permissions, generated from the grant table. Decision 010.

The grant table says what a role may publish and subscribe to. A broker
enforces the same thing in its own language, and a permission list maintained
beside the grants it mirrors is two policies that have to agree. v1's recorded
failures are what policy in two places looks like when they stop agreeing.

So this generates one from the other, and `--check` fails when the committed
file has drifted, exactly as the route manifest does for the platform.

What it does not yet derive is a component's own permissions. The runtime's
user is broad here, and narrowing it means reading the topic registry, which
lives in meridian-design and is not vendored into this repository. Queued
rather than quietly approximated.

Usage:  python3 tools/nats_permissions.py [--grants deploy/grants.example.json]
        python3 tools/nats_permissions.py --check
Exit:   0 current, 1 drifted or unreadable
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

HEADER = """\
# Generated by tools/nats_permissions.py from the grant table. Do not edit.
#
# The grant table is the policy; this is the broker saying the same thing in
# its own language. Run `make nats-permissions` after changing grants.

"""

# Where a reply lands. A caller has to hear its own answer, and a responder has
# to be able to reply to whoever asked; NATS scopes the second to inboxes the
# responder actually received, which is tighter than any list we could write.
INBOX = "_INBOX.>"


def subject(pattern: str) -> str:
    """Our pattern in the broker's grammar.

    `*` is one segment in both. `**` is a tail of one or more, which is `>`,
    and the grammar already restricts it to the tail, so this cannot produce a
    subject that means something else.
    """
    if pattern == "**":
        return ">"
    if pattern.endswith(".**"):
        return f"{pattern[:-3]}.>"
    return pattern


def rendered(grants: dict) -> str:
    roles = grants.get("roles") or {}
    lines = [HEADER, "authorization {", "  users = ["]

    # The deployment's own components. Broad, and named as the gap it is.
    lines.append("    # The runtime's components. Broad until a component's")
    lines.append("    # permissions are derived from the topic registry.")
    lines.append(
        '    { user: runtime, password: $MERIDIAN_NATS_RUNTIME, '
        'permissions: { publish: { allow: [">"] }, subscribe: { allow: [">"] } } }'
    )

    for role in sorted(roles):
        table = roles[role] or {}
        publish = sorted({subject(topic) for topic in table.get("publish") or []})
        subscribe = sorted({subject(topic) for topic in table.get("subscribe") or []})

        # A caller must hear its own answers, and a responder must be able to
        # reply. Neither widens what the role may ask or say.
        publish.append(INBOX)
        subscribe.append(INBOX)

        variable = f"$MERIDIAN_NATS_{role.upper().replace('-', '_')}"
        lines.append(
            f"    {{ user: {role}, password: {variable}, permissions: {{ "
            f"publish: {{ allow: {json.dumps(publish)} }}, "
            f"subscribe: {{ allow: {json.dumps(subscribe)} }}, "
            f"allow_responses: true }} }}"
        )

    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grants", default="deploy/grants.example.json")
    parser.add_argument("--out", default="deploy/nats/permissions.conf")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    grants_path = pathlib.Path(args.grants)
    if not grants_path.exists():
        print(f"nats-permissions: no grant table at {grants_path}", file=sys.stderr)
        return 1

    wanted = rendered(json.loads(grants_path.read_text(encoding="utf-8")))
    out = pathlib.Path(args.out)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current == wanted:
            print(f"nats-permissions OK: {out} matches the grant table")
            return 0
        print(
            f"nats-permissions FAILED: {out} has drifted from {grants_path}.\n"
            "  Run `make nats-permissions`.",
            file=sys.stderr,
        )
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(wanted, encoding="utf-8")
    print(f"nats-permissions: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
