#!/usr/bin/env python3
"""Broker permissions, generated from the grant table. Decision 010.

One credential per plugin instance, not per role. Two plugins sharing a role
would otherwise be able to publish as each other: the grant table writes
`platform.custody.*.event.sync-status`, and that `*` is the instance segment,
so a role-wide credential carries the right to speak as every instance of it.
Substituting the instance identifier is what makes a launch identity mean
something at the broker rather than only inside the sidecar.

The grant table says what a role may publish and subscribe to. A broker
enforces the same thing in its own language, and a permission list maintained
beside the grants it mirrors is two policies that have to agree. v1's recorded
failures are what policy in two places looks like when they stop agreeing.

So this generates one from the other, and `--check` fails when the committed
file has drifted, exactly as the route manifest does for the platform.

What it does not yet derive is a component's own permissions. The runtime's
user is broad here, and narrowing it means reading the topic registry, which
lives in meridian-design and is not vendored into this repository. Queued
rather than quietly approximated.

Usage:  python3 tools/nats_permissions.py [--grants deploy/grants.example.json]
        python3 tools/nats_permissions.py --check
Exit:   0 current, 1 drifted or unreadable
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

HEADER = """\
# Generated by tools/nats_permissions.py from the grant table. Do not edit.
#
# The grant table is the policy; this is the broker saying the same thing in
# its own language. Run `make nats-permissions` after changing grants.

"""

# Where a reply lands. A caller has to hear its own answer, and a responder has
# to be able to reply to whoever asked; NATS scopes the second to inboxes the
# responder actually received, which is tighter than any list we could write.
INBOX = "_INBOX.>"

# Where development identities live. Merged only when asked for, and the result
# is not what a chart ships.
DEV_USERS = "deploy/nats/dev-users.json"


def subject(pattern: str) -> str:
    """Our pattern in the broker's grammar.

    `*` is one segment in both. `**` is a tail of one or more, which is `>`,
    and the grammar already restricts it to the tail, so this cannot produce a
    subject that means something else.
    """
    if pattern == "**":
        return ">"
    if pattern.endswith(".**"):
        return f"{pattern[:-3]}.>"
    return pattern


def scoped(pattern: str, instance_id: str, role: str) -> str:
    """The instance's own version of a topic it publishes.

    `platform.<domain>.<instance>.<kind>.<action>` is the shape the registry
    gives an instance-scoped topic, so a `*` in that position is the instance
    slot and nothing else. Substituting it is the difference between a
    credential that may speak for this connector and one that may speak for
    every connector of its kind.

    Two conditions, and the second was learned by getting it wrong: the domain
    must be the instance's own. A dashboard subscribes to
    `platform.custody.*.event.sync-status` to hear every connector, and
    rewriting that to its own identifier leaves it subscribed to a topic
    nobody publishes. You may speak only as yourself; you may listen to
    everyone your grants allow.
    """
    segments = pattern.split(".")
    if len(segments) == 5 and segments[2] == "*" and segments[1] == role:
        segments[2] = instance_id
        return ".".join(segments)
    return pattern


def permissions_for(grants: dict, role: str, tags: list[str], instance_id: str) -> tuple[list, list]:
    """What one instance may publish and subscribe to.

    A role and each of its tags are looked up in the one table and unioned,
    which is what the grant table's own note says, so a tag is an entry there
    like any other.
    """
    roles = grants.get("roles") or {}
    publish: set[str] = set()
    subscribe: set[str] = set()

    for name in [role, *tags]:
        table = roles.get(name) or {}
        # Publishing is narrowed to this instance; subscribing is not, because
        # hearing every instance of another role is what a dashboard is for.
        publish.update(
            subject(scoped(topic, instance_id, role)) for topic in table.get("publish") or []
        )
        subscribe.update(subject(topic) for topic in table.get("subscribe") or [])

    return sorted(publish), sorted(subscribe)


# The components this deployment's runtime hosts. Both stores are in one
# process today and become two, at which point each gets its own credential
# with its own half of this: the manifest already says which topics are whose.
COMPONENTS = ("reference", "kernel")


def component_permissions(manifest: str) -> tuple[list[str], list[str]]:
    """What the runtime's components may publish and subscribe to.

    Derived from the registry's own publisher and subscriber columns, vendored
    here by meridian-design, rather than granted wholesale. A component that
    may publish anything can publish as a plugin, and the boundary this whole
    decision is about would hold everywhere except at the thing most able to
    ignore it.
    """
    publish: set[str] = set()
    subscribe: set[str] = set()

    for line in manifest.splitlines():
        if line.startswith("#") or line.startswith("topic\t") or not line.strip():
            continue
        topic, _kind, publisher, subscriber = line.split("\t")
        publishers = {part.strip() for part in publisher.split(",")}
        subscribers = {part.strip() for part in subscriber.split(",")}

        if publishers & set(COMPONENTS):
            publish.add(subject(topic))
        if subscribers & set(COMPONENTS):
            subscribe.add(subject(topic))

    return sorted(publish), sorted(subscribe)


def rendered(grants: dict, instances: dict, manifest: str, extras: dict | None = None) -> str:
    roles = grants.get("roles") or {}
    lines = [HEADER, "authorization {", "  users = ["]

    publish, subscribe = component_permissions(manifest)

    # A component answers calls, so it subscribes to the topics it serves and
    # replies to whoever asked; allow_responses scopes that to inboxes it
    # actually received, which is tighter than any list.
    publish.append(INBOX)
    subscribe.append(INBOX)

    lines.append("    # The runtime's components, from the registry's own columns.")
    lines.append(
        f"    {{ user: runtime, password: $MERIDIAN_NATS_RUNTIME, permissions: {{ "
        f"publish: {{ allow: {json.dumps(publish)} }}, "
        f"subscribe: {{ allow: {json.dumps(subscribe)} }}, "
        f"allow_responses: true }} }}"
    )

    for instance in instances.get("instances") or []:
        instance_id = instance["instance_id"]
        role = instance.get("role") or ""
        tags = instance.get("tags") or []

        if role and role not in roles and not any(tag in roles for tag in tags):
            raise SystemExit(
                f"nats-permissions: {instance_id} is launched as `{role}`, which the "
                "grant table does not define. An instance with no grants has no bus."
            )

        publish, subscribe = permissions_for(grants, role, tags, instance_id)

        # A caller must hear its own answers, and a responder must be able to
        # reply. Neither widens what the instance may ask or say.
        publish.append(INBOX)
        subscribe.append(INBOX)

        variable = f"$MERIDIAN_NATS_{instance_id.upper().replace('-', '_')}"
        lines.append(
            f"    # {instance_id}, launched as {role}"
            + (f" with {', '.join(tags)}" if tags else "")
        )
        lines.append(
            f"    {{ user: {instance_id}, password: {variable}, permissions: {{ "
            f"publish: {{ allow: {json.dumps(publish)} }}, "
            f"subscribe: {{ allow: {json.dumps(subscribe)} }}, "
            f"allow_responses: true }} }}"
        )

    for extra in (extras or {}).get("users") or []:
        publish = list(extra.get("publish") or [])
        subscribe = list(extra.get("subscribe") or [])
        lines.append(f"    # {extra['user']}: a development identity, from {DEV_USERS}")
        lines.append(
            f"    {{ user: {extra['user']}, password: ${extra['password_env']}, permissions: {{ "
            f"publish: {{ allow: {json.dumps(publish)} }}, "
            f"subscribe: {{ allow: {json.dumps(subscribe)} }}, "
            f"allow_responses: true }} }}"
        )

    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grants", default="deploy/grants.example.json")
    parser.add_argument("--instances", default="deploy/instances.example.json")
    parser.add_argument("--topics", default="deploy/topics.tsv")
    parser.add_argument(
        "--with-dev-users",
        action="store_true",
        help="merge deploy/nats/dev-users.json, for running this repository's tests",
    )
    parser.add_argument("--out", default="deploy/nats/permissions.conf")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    grants_path = pathlib.Path(args.grants)
    if not grants_path.exists():
        print(f"nats-permissions: no grant table at {grants_path}", file=sys.stderr)
        return 1

    instances_path = pathlib.Path(args.instances)
    if not instances_path.exists():
        print(f"nats-permissions: no launch configuration at {instances_path}", file=sys.stderr)
        return 1

    topics_path = pathlib.Path(args.topics)
    if not topics_path.exists():
        print(
            f"nats-permissions: no topic manifest at {topics_path}. It is generated by "
            "meridian-design's `make component-topics`.",
            file=sys.stderr,
        )
        return 1

    extras = None
    if args.with_dev_users:
        extras = json.loads(pathlib.Path(DEV_USERS).read_text(encoding="utf-8"))

    wanted = rendered(
        json.loads(grants_path.read_text(encoding="utf-8")),
        json.loads(instances_path.read_text(encoding="utf-8")),
        topics_path.read_text(encoding="utf-8"),
        extras,
    )
    out = pathlib.Path(args.out)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current == wanted:
            print(f"nats-permissions OK: {out} matches the grant table")
            return 0
        print(
            f"nats-permissions FAILED: {out} has drifted from {grants_path}.\n"
            "  Run `make nats-permissions`.",
            file=sys.stderr,
        )
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(wanted, encoding="utf-8")
    print(f"nats-permissions: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
